### PR TITLE
config: fix access for config and history file

### LINKED ISSUE #157: apikey and secretkey stored in plain text in (world readable) history file
When `set apikey xyz` or `set secretkey xyz` are executed on the cloudmonkey prompt, the command is stored verbatim into the history, potentially exposing sensitive data into a file that [is world readable by default](https://github.com/chzyer/readline/blob/7f93d88cd5ffa0e805d58d2f9fc3191be15ec668/history.go#L69).

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes #157

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

File: config/config.go [hunk 1]
```diff
@@ -391,6 +396,12 @@ func (c *Config) UpdateConfig(key string, value string, update bool) {
 	}
 }
 
+func makeFileGroupPrivate(filePath string) {
+	if fi, err := os.Stat(filePath); err == nil && fi.Mode().IsRegular() {
+		_ = os.Chmod(filePath, 0660)
```
Comment (DaanHoogland) [inline config/config.go:401]:
```suggestion
		_ = os.Chmod(filePath, 0770)
```

**Comment by DaanHoogland** [comment]
works as expected but I want to sugest being a touch more restrictive in the access rights, i.e. no group access.

File: config/config.go (hunk 1 above)
Comment (shwstppr) [reply config/config.go]: done
